name: SonarQube analysis
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:
permissions:
  pull-requests: read # allows SonarQube to decorate PRs with analysis results

jobs:
  Analysis:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Analyze with SonarQube
        uses: SonarSource/sonarqube-scan-action@7295e71c9583053f5bf40e9d4068a0c974603ec8
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}   # Needed to get PR information
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}     # Must be added in repo Settings > Secrets and variables > Actions
        with:
          args:
            -Dsonar.projectKey=mtarig398-tech_lan-chat-pro
            -Dsonar.organization=mtarig398-tech
